[package]
name = "serde_versioned"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_versioned_derive = { path = "../serde_versioned_derive" }
serde = { version = "1.0", features = ["derive"] }